# Generated by Django 6.0.2 on 2026-02-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
